### ISSUE TITLE
Prepare 0.4.0 release

### ISSUE THREAD

**Issue by jmadureira** [jmadureira/netdata-cookbook#24]
Following on the request made by Frans-Jan van Steenbeek (see #23 ) to release a new version of the cookbook supporting binary installations there are a couple of things I wanted to add to the discussion:
- This should be a minor release since new features will be added.
- Even though this feature already includes integration tests a request was made to @salsa-dev to create a pull request with chef specs for additional safety.

As such I have no problem in releasing version 0.4.0 as is. If anyone has anything to add please do so.

**Comment by nictrix** [comment]
I would like to add unit tests for the logic of using a binary or source install. Other than that, it looks fine.

Though in regards to `compat_resource` - should we add that as a dependency until EOL chef-client 12? - And at that point, we could move this cookbook to 1.0.0 and remove dependencies and the depreciated features?

**Comment by salsa-dev** [comment]
There is one more issue to discuss before release:
If binary_package option is set to 'netdata-latest.gz.run' (which is the default) NetData will be updated to the latest version available every chef-client run. Thus we have the default autoupdate performed by Chef.

It should be noted in README but before making PR I propose to discuss whether everyone agrees on such a default behaviour.

**Comment by salsa-dev** [comment]
Regarding "compat_resource" I thought accumulator support from chef-client 12.16.x as noted https://gist.github.com/lamont-granquist/b569d0086d19739ebeb3e8c7ab1d65bc#the-delayed_action-helper
If specifying dependency solves the issue It solves the problem for those having old chef-client in prod (including myself).
+1 to supporting chef-client 12 until EOL.

**Comment by nictrix** [comment]
Having Chef auto-update Netdata to the latest package will definitely be a surprise and I believe the source install got changed to master also? Which makes both of the install methods auto-update?

I don't think it's a bad thing, though if Netdata were to change how they did the installs or changed the packages then the cookbook could fail.

+1 on leaving it auto-updating on default call of `netdata_install` resource
+1 on supporting chef 12 until EOL
+1 on creating unit tests to check the logic between binary and source installs.
